"""add image processing fields

Revision ID: da8c54fb0977
Revises: 272c7b1ee1bc
Create Date: 2026-08-19 10:35:55.734530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8c54fb0977'
down_revision: Union[str, Sequence[str], None] = '272c7b1ee1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('product_images', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('product_images', sa.Column('blur_data_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'blur_data_url')
    op.drop_column('product_images', 'height')
    op.drop_column('product_images', 'width')
    # ### end Alembic commands ###
